login.i18n(f[1],i,"Please login");
login.i18n(f[1],i,"Login");
login.i18n(f[1],i,"Password");
login.i18n(f[1],i,"Login");
layout.i18n(f[1],i,"Hi Stranger, this is protected area.");
layout.i18n(f[1],i,"Please contact site owner for account if you need it.");
layout.i18n(f[1],i,"Login");
layout.i18n(f[1],i,"if you have it already");
layout.i18n(f[1],i,"Hi");
layout.i18n(f[1],i,"Logout");
layout.i18n(f[1],i,"Copyright by PushOk Software");
accessDenied.i18n(f[1],i,"Access denied");
accessDenied.i18n(f[1],i,"You do not have permission.");
accessDenied.i18n(f[1],i,"Please login");
accessDenied.i18n(f[1],i,"Login");
accessDenied.i18n(f[1],i,"Password");
accessDenied.i18n(f[1],i,"Login");
user.i18n(f[1],i,"Your prefferences");
user.i18n(f[1],i,"edit");
user.i18n(f[1],i,"First name");
user.i18n(f[1],i,"Last name");
user.i18n(f[1],i,"Login");
user.i18n(f[1],i,"Gui language");
user.i18n(f[1],i,"Timezone");
user.i18n(f[1],i,"Your permissions");
user.i18n(f[1],i,"edit");
user.i18n(f[1],i,"Account prefferences");
user.i18n(f[1],i,"First name");
user.i18n(f[1],i,"Last name");
user.i18n(f[1],i,"Login");
user.i18n(f[1],i,"Change password");
user.i18n(f[1],i,"Old password");
user.i18n(f[1],i,"New password");
user.i18n(f[1],i,"Retype new password");
user.i18n(f[1],i,"Gui language");
user.i18n(f[1],i,"Timezone");
index.i18n(f[1],i,"Welcome to SkiLap!");
index.i18n(f[1],i,"Following modules are available:");
index.i18n(f[1],i,"Please note, you might need to log-in to get access to some modules.");
