user_prefs.i18n(f[1],i,"Account prefferences");
user_prefs.i18n(f[1],i,"First name");
user_prefs.i18n(f[1],i,"Last name");
user_prefs.i18n(f[1],i,"Login");
user_prefs.i18n(f[1],i,"Change password");
user_prefs.i18n(f[1],i,"Password");
user_prefs.i18n(f[1],i,"Gui language");
user_prefs.i18n(f[1],i,"Russian");
user_prefs.i18n(f[1],i,"English");
user_prefs.i18n(f[1],i,"Timezone");
systemsetings.i18n(f[1],i,"Apply");
systemsetings.i18n(f[1],i,"Close");
systemsetings.i18n(f[1],i,"Apply");
systemsetings.i18n(f[1],i,"Close");
systemsetings.i18n(f[1],i,"Guest prefferences");
systemsetings.i18n(f[1],i,"edit");
systemsetings.i18n(f[1],i,"Gui language");
systemsetings.i18n(f[1],i,"Timezone");
systemsetings.i18n(f[1],i,"Guest permissions");
systemsetings.i18n(f[1],i,"edit");
systemsetings.i18n(f[1],i,"Account prefferences");
systemsetings.i18n(f[1],i,"Gui language");
systemsetings.i18n(f[1],i,"Timezone");
login.i18n(f[1],i,"Please login");
login.i18n(f[1],i,"Login");
login.i18n(f[1],i,"Password");
login.i18n(f[1],i,"Login");
userprefferences.i18n(f[1],i,"Apply");
userprefferences.i18n(f[1],i,"Close");
userprefferences.i18n(f[1],i,"Account prefferences");
userprefferences.i18n(f[1],i,"First name");
userprefferences.i18n(f[1],i,"Last name");
userprefferences.i18n(f[1],i,"Login");
userprefferences.i18n(f[1],i,"Change password");
userprefferences.i18n(f[1],i,"Password");
userprefferences.i18n(f[1],i,"Gui language");
userprefferences.i18n(f[1],i,"Russian");
userprefferences.i18n(f[1],i,"English");
userprefferences.i18n(f[1],i,"Timezone");
layout.i18n(f[1],i,"Core");
layout.i18n(f[1],i,"My account");
layout.i18n(f[1],i,"Manage users");
layout.i18n(f[1],i,"System settings");
layout.i18n(f[1],i,"Logout");
layout.i18n(f[1],i,"Copyright by PushOk Software");
accessDenied.i18n(f[1],i,"Hi Stranger, this is protected area.");
accessDenied.i18n(f[1],i,"Please contact site owner for account if you need it.");
accessDenied.i18n(f[1],i,"Login");
accessDenied.i18n(f[1],i,"if you have it already");
userpermisions.i18n(f[1],i,"Apply");
userpermisions.i18n(f[1],i,"Close");
userpermisions.i18n(f[1],i,"Edit permissions");
users.i18n(f[1],i,"Are you sure?");
users.i18n(f[1],i,"Apply");
users.i18n(f[1],i,"Close");
users.i18n(f[1],i,"Add new user");
users.i18n(f[1],i,"First name");
users.i18n(f[1],i,"Last name");
users.i18n(f[1],i,"Login");
users.i18n(f[1],i,"Action");
users.i18n(f[1],i,"Edit");
users.i18n(f[1],i,"Permissions");
users.i18n(f[1],i,"Delete");
users.i18n(f[1],i,"Add new user");
users.i18n(f[1],i,"First name");
users.i18n(f[1],i,"Last name");
users.i18n(f[1],i,"Login");
users.i18n(f[1],i,"Password");
users.i18n(f[1],i,"Gui language");
users.i18n(f[1],i,"Timezone");
user.i18n(f[1],i,"Your prefferences");
user.i18n(f[1],i,"edit");
user.i18n(f[1],i,"First name");
user.i18n(f[1],i,"Last name");
user.i18n(f[1],i,"Login");
user.i18n(f[1],i,"Gui language");
user.i18n(f[1],i,"Timezone");
user.i18n(f[1],i,"Your permissions");
user.i18n(f[1],i,"edit");
index.i18n(f[1],i,"Welcome to SkiLap!");
index.i18n(f[1],i,"Following modules are available:");
index.i18n(f[1],i,"Please note, you might need to log-in to get access to some modules.");
