account.i18n(f[1],i,"Date");
account.i18n(f[1],i,"Num");
account.i18n(f[1],i,"Description");
account.i18n(f[1],i,"Transfer");
account.i18n(f[1],i,"Receive");
account.i18n(f[1],i,"Spend");
account.i18n(f[1],i,"Balance");
nav.i18n(f[1],i,"Data");
nav.i18n(f[1],i,"New register");
nav.i18n(f[1],i,"Import Gnu Cash");
nav.i18n(f[1],i,"Import Skilap Cash");
nav.i18n(f[1],i,"Export Skilap Cash");
nav.i18n(f[1],i,"View");
nav.i18n(f[1],i,"Home");
nav.i18n(f[1],i,"Accounts");
nav.i18n(f[1],i,"Report");
nav.i18n(f[1],i,"Spend/receive bar chart");
nav.i18n(f[1],i,"Spend/receive pie chart");
restoredefaults.i18n(f[1],i,"Create new cash register");
restoredefaults.i18n(f[1],i,"Attention! Your existing data will be overwritten upon complete.");
restoredefaults.i18n(f[1],i,"Default currency");
restoredefaults.i18n(f[1],i,"Template");
restoredefaults.i18n(f[1],i,"Default accounts");
restoredefaults.i18n(f[1],i,"Empty");
restoredefaults.i18n(f[1],i,"Confirm");
restoredefaults.i18n(f[1],i,"Cancel");
report.i18n(f[1],i,"Expense");
report.i18n(f[1],i,"Income");
report.i18n(f[1],i,"Apply");
report.i18n(f[1],i,"Close");
report.i18n(f[1],i,"Report settings");
report.i18n(f[1],i,"Start date");
report.i18n(f[1],i,"End date");
report.i18n(f[1],i,"Max account");
report.i18n(f[1],i,"Report name");
report.i18n(f[1],i,"Account type");
report.i18n(f[1],i,"Expense");
report.i18n(f[1],i,"Income");
report.i18n(f[1],i,"Report settings");
index.i18n(f[1],i,"Assets");
index.i18n(f[1],i,"Liabilities");
