account.i18n(f[1],i,"Date");
account.i18n(f[1],i,"Num");
account.i18n(f[1],i,"Description");
account.i18n(f[1],i,"Transfer");
account.i18n(f[1],i,"Receive");
account.i18n(f[1],i,"Spend");
account.i18n(f[1],i,"Balance");
accounts-create.i18n(f[1],i,"Apply");
accounts-create.i18n(f[1],i,"Close");
accounts-create.i18n(f[1],i,"Account properties");
accounts-create.i18n(f[1],i,"Name");
accounts-create.i18n(f[1],i,"Parent account");
accounts-create.i18n(f[1],i,"Root");
accounts-create.i18n(f[1],i,"Curency");
accounts-create.i18n(f[1],i,"Type");
accounts-create.i18n(f[1],i,"Hidden");
accounts-create.i18n(f[1],i,"Placeholder");
accounts-delete.i18n(f[1],i,"Apply");
accounts-delete.i18n(f[1],i,"Close");
accounts-delete.i18n(f[1],i,"Delete account");
accounts-delete.i18n(f[1],i,"Transactions");
accounts-delete.i18n(f[1],i,"If this account contans transactions. What would you like to do with these transactions?");
accounts-delete.i18n(f[1],i,"Delete");
accounts-delete.i18n(f[1],i,"Move to");
accounts-delete.i18n(f[1],i,"Sub-accounts");
accounts-delete.i18n(f[1],i,"If this account contans sub-accounts. What would you like to do with these sub-accounts?");
accounts-delete.i18n(f[1],i,"Delete");
accounts-delete.i18n(f[1],i,"Move to");
accounts-delete.i18n(f[1],i,"Sub-account transactions");
accounts-delete.i18n(f[1],i,"If one or more sub-account contan transactions. What would you like to do with these transactios?");
accounts-delete.i18n(f[1],i,"Delete");
accounts-delete.i18n(f[1],i,"Move to");
nav.i18n(f[1],i,"Data");
nav.i18n(f[1],i,"New register");
nav.i18n(f[1],i,"Import Gnu Cash");
nav.i18n(f[1],i,"Import Skilap Cash");
nav.i18n(f[1],i,"Export Skilap Cash");
nav.i18n(f[1],i,"View");
nav.i18n(f[1],i,"Home");
nav.i18n(f[1],i,"Accounts");
nav.i18n(f[1],i,"Rate Currency Editor");
nav.i18n(f[1],i,"Settings");
nav.i18n(f[1],i,"Report");
nav.i18n(f[1],i,"Spend/receive bar chart");
nav.i18n(f[1],i,"Spend/receive pie chart");
priceeditor.i18n(f[1],i,"Click and drag in the plot area to zoom in");
priceeditor.i18n(f[1],i,"Drag your finger over the plot to zoom in");
priceeditor.i18n(f[1],i,"Exchange rate");
priceeditor.i18n(f[1],i,"to");
priceeditor.i18n(f[1],i,"exchange rate");
priceeditor.i18n(f[1],i,"Add Rate Currency");
priceeditor.i18n(f[1],i,"Edit Rate Currency");
priceeditor.i18n(f[1],i,"Apply");
priceeditor.i18n(f[1],i,"Close");
priceeditor.i18n(f[1],i,"Delete");
priceeditor.i18n(f[1],i,"Cancel");
priceeditor.i18n(f[1],i,"Select pair of currencies to edit rate exchanging currency");
priceeditor.i18n(f[1],i,"Apply");
priceeditor.i18n(f[1],i,"Add");
priceeditor.i18n(f[1],i,"Edit");
priceeditor.i18n(f[1],i,"Delete");
accounts-tree_item.i18n(f[1],i,"edit");
accounts-tree_item.i18n(f[1],i,"delete");
restoredefaults.i18n(f[1],i,"Create new cash register");
restoredefaults.i18n(f[1],i,"Attention! Your existing data will be overwritten upon complete.");
restoredefaults.i18n(f[1],i,"Default currency");
restoredefaults.i18n(f[1],i,"Template");
restoredefaults.i18n(f[1],i,"Default accounts");
restoredefaults.i18n(f[1],i,"Empty");
restoredefaults.i18n(f[1],i,"Confirm");
restoredefaults.i18n(f[1],i,"Cancel");
priceeditor_table.i18n(f[1],i,"Date");
priceeditor_table.i18n(f[1],i,"Rate currency");
priceeditor_table.i18n(f[1],i,"Raw value");
priceeditor_table.i18n(f[1],i,"Delete confirmation");
priceeditor_table.i18n(f[1],i,"Delete selected rate currency?");
settings.i18n(f[1],i,"Apply");
settings.i18n(f[1],i,"Close");
settings.i18n(f[1],i,"Cash settings");
settings.i18n(f[1],i,"Default Currency");
import.i18n(f[1],i,"Import Gnu Cash");
import.i18n(f[1],i,"Import Skilap Cash");
import.i18n(f[1],i,"Attention! Your existing data will be overwritten upon complete.");
import.i18n(f[1],i,"Select file for import");
import.i18n(f[1],i,"Browse");
import.i18n(f[1],i,"Next");
import.i18n(f[1],i,"File parsed. It contains");
import.i18n(f[1],i,"transactions");
import.i18n(f[1],i,"accounts");
import.i18n(f[1],i,"Next");
import.i18n(f[1],i,"Data saved");
import.i18n(f[1],i,"transactions");
import.i18n(f[1],i,"and");
import.i18n(f[1],i,"accounts");
import.i18n(f[1],i,"were imported");
import.i18n(f[1],i,"Finish");
import.i18n(f[1],i,"Wrong data. Please try again.");
report.i18n(f[1],i,"Expense");
report.i18n(f[1],i,"Income");
report.i18n(f[1],i,"Apply");
report.i18n(f[1],i,"Close");
report.i18n(f[1],i,"Report settings");
report.i18n(f[1],i,"Start date");
report.i18n(f[1],i,"End date");
report.i18n(f[1],i,"Max account");
report.i18n(f[1],i,"Report name");
report.i18n(f[1],i,"Account type");
report.i18n(f[1],i,"Expense");
report.i18n(f[1],i,"Income");
report.i18n(f[1],i,"Report settings");
accounts-tree.i18n(f[1],i,"Add new account");
accounts-tree.i18n(f[1],i,"denotes hidden accounts");
index.i18n(f[1],i,"Assets");
index.i18n(f[1],i,"Liabilities");
